FROM golang:1.18

WORKDIR /app/

RUN apt-get update && apt-get install -y librdkafka-dev

RUN go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

CMD [ "tail", "-f", "/dev/null" ]